import { Manrope, Bangers, DM_Sans } from 'next/font/google'
import type { Metadata } from 'next'
import './globals.css'
import AppNavbar from '@/components/client/shared/AppNavbar'

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
})

const bangers = Bangers({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-display',
  weight: '400',
})

const dm_sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='es'>
      <body
        className={`${manrope.variable} ${bangers.variable} ${dm_sans.variable} antialiased`}
      >
        <link rel='preconnect' href='https://fonts.googleapis.com'></link>
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        ></link>
        <link
          href='https://fonts.googleapis.com/css2?family=Google+Sans+Code:ital,wght@0,300..800;1,300..800&display=swap'
          rel='stylesheet'
        ></link>
        <AppNavbar />
        {children}
      </body>
    </html>
  )
}
